server.error.include-message=always
server.error.include-binding-errors=always
# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/superdrive
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.boot.allow_jdbc_metadata_access=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.show-sql=true
# Initialize schema using schema.sql
spring.sql.init.mode=always
spring.sql.init.continue-on-error=false
